---

- name: Download Limesurvey package
  get_url: url={{ limesurvey__package_url }} dest=/tmp/{{ limesurvey__package }}

- name: Extract Limesurvey package
  unarchive: copy=no src=/tmp/{{ limesurvey__package }} dest={{ limesurvey__www }} group=users owner=root creates={{ limesurvey__www }}/limesurvey

- name: Fix permissions
  file: path={{ limesurvey__www }}/{{ item }} owner={{ limesurvey__user }} recurse=yes
  with_items:
    - limesurvey/tmp
    - limesurvey/upload
    - limesurvey/application/config

- name: Transfer SQL file
  template: src=limesurvey.sql.j2 dest=/tmp/limesurvey.sql mode=0600

- name: Import empty SQL database
  mysql_db: state=import name={{ limesurvey__database_name }} target=/tmp/limesurvey.sql login_host=localhost

- name: Transfer Limesurvey configuration file
  template: src=config.php.j2 dest={{ limesurvey__www }}/limesurvey/application/config/config.php owner={{ limesurvey__webserver_user }} mode=0644
